### ISSUE TITLE
i can't use this driver in ubuntu18.04

### ISSUE THREAD

**Issue by GYUMO** [HunterXuan/rtl8812AU_8821AU_linux#1]
`<pre>Makefile:975: &quot;Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel&quot;
  CC [M]  /home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/core/rtw_cmd.o
In file included from <b>/home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/include/osdep_service.h:41:0</b>,
                 from <b>/home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/include/drv_types.h:32</b>,
                 from <b>/home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/core/rtw_cmd.c:22</b>:
<b>/home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/include/osdep_service_linux.h:</b> In function ‘<b>_init_timer</b>’:
<b>/home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/include/osdep_service_linux.h:267:8:</b> <font color="#EF2929"><b>error: </b></font>‘<b>_timer {aka struct timer_list}</b>’ has no member named ‘<b>data</b>’
  ptimer<font color="#EF2929"><b>-&gt;</b></font>data = (unsigned long)cntx;
        <font color="#EF2929"><b>^~</b></font>
<b>/home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/include/osdep_service_linux.h:268:2:</b> <font color="#EF2929"><b>error: </b></font>implicit declaration of function ‘<b>init_timer</b>’; did you mean ‘<b>_init_timer</b>’? [<font color="#EF2929"><b>-Werror=implicit-function-declaration</b></font>]
  <font color="#EF2929"><b>init_timer</b></font>(ptimer);
  <font color="#EF2929"><b>^~~~~~~~~~</b></font>
  <font color="#4E9A06">_init_timer</font>
In file included from <b>/home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/include/drv_types.h:32:0</b>,
                 from <b>/home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/core/rtw_cmd.c:22</b>:
<b>/home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/include/osdep_service.h:</b> In function ‘<b>thread_enter</b>’:
<b>/home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/include/osdep_service.h:343:2:</b> <font color="#EF2929"><b>error: </b></font>implicit declaration of function ‘<b>allow_signal</b>’; did you mean ‘<b>do_signal</b>’? [<font color="#EF2929"><b>-Werror=implicit-function-declaration</b></font>]
  <font color="#EF2929"><b>allow_signal</b></font>(SIGTERM);
  <font color="#EF2929"><b>^~~~~~~~~~~~</b></font>
  <font color="#4E9A06">do_signal</font>
<b>/home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/include/osdep_service.h:</b> In function ‘<b>flush_signals_thread</b>’:
<b>/home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/include/osdep_service.h:353:6:</b> <font color="#EF2929"><b>error: </b></font>implicit declaration of function ‘<b>signal_pending</b>’; did you mean ‘<b>timer_pending</b>’? [<font color="#EF2929"><b>-Werror=implicit-function-declaration</b></font>]
  if (<font color="#EF2929"><b>signal_pending</b></font> (current))
      <font color="#EF2929"><b>^~~~~~~~~~~~~~</b></font>
      <font color="#4E9A06">timer_pending</font>
<b>/home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/include/osdep_service.h:355:3:</b> <font color="#EF2929"><b>error: </b></font>implicit declaration of function ‘<b>flush_signals</b>’; did you mean ‘<b>do_signal</b>’? [<font color="#EF2929"><b>-Werror=implicit-function-declaration</b></font>]
   <font color="#EF2929"><b>flush_signals</b></font>(current);
   <font color="#EF2929"><b>^~~~~~~~~~~~~</b></font>
   <font color="#4E9A06">do_signal</font>
In file included from <b>/home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/include/drv_types.h:95:0</b>,
                 from <b>/home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/core/rtw_cmd.c:22</b>:
<b>/home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/include/hal_com.h:</b> At top level:
<b>/home/maomao/document/drvers/driver/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51/include/hal_com.h:412:13:</b> <font color="#EF2929"><b>error: </b></font>‘<b>file_path</b>’ redeclared as different kind of symbol
 extern char <font color="#EF2929"><b>file_path</b></font>[PATH_LENGTH_MAX];
             <font color="#EF2929"><b>^~~~~~~~~</b></font>
</pre>`

**Comment by HunterXuan** [comment]
according to the errors, I think that libelf-dev, libelf-devel or elfutils-libelf-devel should be installed.

**Comment by GYUMO** [comment]
谢谢您啦
